Cleanup: code folds, variables; closes nima/site#21
Cleaned up the code presentation and folds, and changed all global
variables to force-check themselves; for example `${GLOBAL_VAR?}'.

diff --git a/module/cpf b/module/cpf
--- a/module/cpf
+++ b/module/cpf
@@ -1,14 +1,146 @@
 # vim: tw=0:ts=4:sw=4:et:ft=bash
 
+:<<[core:docstring]
+Site's color printf module
+[core:docstring]
+
+#. The Color PrintF Module -={
 : ${SITE_IN_COLOR?}
 
-function is_fmt() {
+#declare -i ncolors=$(tput colors)
+#if [ ${ncolors:=-2} -ge 8 ]; then
+declare -A COLORS=(
+    [N]="$(tput sgr0)"      [R]="$(tput rev)"
+
+    [+ul]="$(tput smul)"    [-ul]="$(tput rmul)"
+    [+st]="$(tput smso)"    [-st]="$(tput rmso)"
+    [+bo]="$(tput bold)"    [-bo]="$(tput sgr0)"
+
+    [bl]="$(tput setaf 0)"  [wh]="$(tput setaf 7)"
+    [r]="$(tput setaf 1)"   [g]="$(tput setaf 2)"
+    [y]="$(tput setaf 3)"   [b]="$(tput setaf 4)"
+    [m]="$(tput setaf 5)"   [c]="$(tput setaf 6)"
+)
+
+#. cpf:module -={
+function ::cpf:module_is_modified() {
+    local -i e=9
+    local profile=$1
+    local module=$2
+    cd ${SITE_CORE?}
+    if [ -e "${SITE_USER_MOD?}/${module}" ]; then
+        local path=$(readlink "${SITE_USER_MOD?}/${module}")
+        local amended=$(:core:git status --porcelain "${path}"|wc -l)
+        [ ${PIPESTATUS[0]} -ne 0 ] || e=${amended}
+    fi
+    #cd ${OLDPWD?}
+
+    return $e
+}
+function ::cpf:module_has_alerts() {
+    local -i e=${CODE_FAILURE?}
+
+    local profile=$1
+    local module=$2
+    if [ -e "${SITE_USER_MOD?}/${module}" ]; then
+        grep -qE "^function ${module}:[a-z0-9]+:alert()" "${SITE_USER_MOD?}/${module}"
+        [ $? -ne 0 ] || e=${CODE_SUCCESS?}
+    fi
+
+    return $e
+}
+function ::cpf:module() {
+    local -r module=$1
+
+    local -i enabled=1
+    local -i alerts=0
+    local -i amended=0
+    local fmt
+    if [ -e ${SITE_CORE_MOD?}/${module} ]; then
+        if ::cpf:module_has_alerts core ${module}; then
+            alerts=1
+            fmt="%{y}"
+        else
+            fmt="%{c}"
+            ::cpf:module_is_modified core ${module}
+            amended=$?
+        fi
+        enabled=${CORE_MODULES[${module}]}
+    elif [ -e ${SITE_USER_MOD?}/${module} ]; then
+        if ::cpf:module_has_alerts ${SITE_PROFILE?} ${module}; then
+            alerts=1
+            fmt="%{y}"
+        else
+            fmt="%{b}"
+            ::cpf:module_is_modified ${SITE_PROFILE?} ${module}
+            amended=$?
+        fi
+        enabled=${USER_MODULES[${module}]}
+    fi
+
+    [ ${amended} -eq 0 ] || fmt+="%{ul}"
+    [ ${enabled} -eq 0 ] || fmt+="%{bo}"
+
+    cpf "${fmt}%s%{N}" ${module}
+}
+#. }=-
+#. cpf:function -={
+function ::cpf:function_has_alerts() {
+    local -i e=${CODE_FAILURE?}
+
+    local profile=$1
+    local module=$2
+    local fn=$3
+    if [ -e "${SITE_USER_MOD?}/${module}" ]; then
+        grep -qE "^function ${module}:${fn}:alert()" "${SITE_USER_MOD?}/${module}"
+        [ $? -ne 0 ] || e=${CODE_SUCCESS?}
+    fi
+
+    return $e
+}
+function ::cpf:function() {
+    local -r module=$1
+    local -r fn=$2
+
+    local -i enabled=1
+    local -i alerts=0
+    local -i amended=0
+    local fmt
+    if [ -e ${SITE_CORE_MOD?}/${module} ]; then
+        if ::cpf:function_has_alerts core ${module} ${fn}; then
+            alerts=1
+            fmt="%{y}"
+        else
+            fmt="%{c}"
+            ::cpf:module_is_modified core ${module}
+            amended=$?
+        fi
+        enabled=${CORE_MODULES[${module}]}
+    elif [ -e ${SITE_USER_MOD?}/${module} ]; then
+        if ::cpf:function_has_alerts ${SITE_PROFILE?} ${module} ${fn}; then
+            alerts=1
+            fmt="%{y}"
+        else
+            fmt="%{b}"
+            ::cpf:module_is_modified ${SITE_PROFILE?} ${module}
+            amended=$?
+        fi
+        enabled=${USER_MODULES[${module}]}
+    fi
+
+    [ ${amended} -eq 0 ] || fmt+="%{ul}"
+    [ ${enabled} -eq 0 ] || fmt+="%{bo}"
+
+    cpf "${fmt}%s %{b:%s}%{N}" ${module} ${fn}
+}
+#. }=-
+
+#. cpf:theme -={
+function ::cpf:is_fmt() {
     grep -qE '%' <<<"$1"
     return $?
 }
 
-#declare -i ncolors=$(tput colors)
-#if [ ${ncolors:=-2} -ge 8 ]; then
 function ::cpf:theme() {
     local e=1
 
@@ -47,7 +179,7 @@ function ::cpf:theme() {
                 #. If a symbol is defined
                 if [ ${#symbol} -gt 0 ]; then
                     #. If the argument is a literal, for example %{@host:myhost}, and NOT %{@host:%s}
-                    if ! is_fmt "${arg}"; then
+                    if ! ::cpf:is_fmt "${arg}"; then
                         #. Add the symbol in now, and unset the symbol variable back to null
                         arg="${symbol}${arg}"
                     fi
@@ -105,22 +237,124 @@ function ::cpf:theme() {
         core:raise EXCEPTION_BAD_FN_CALL "What is your problem?"
     fi
 }
+#. }=-
+#. cpf -={
+function cpf() {
+    #. cpf "%{ul:%s}, %{r}%{bo:%s}, and %{st:%s}%{no}\n" underlined bold standard
+    LC_ALL=C
 
-declare -A COLORS=(
-    [N]="$(tput sgr0)"      [R]="$(tput rev)"
+    #echo "XXX FUNC CALL with ${#}" > /dev/stderr
 
-    [+ul]="$(tput smul)"    [-ul]="$(tput rmul)"
-    [+st]="$(tput smso)"    [-st]="$(tput rmso)"
-    [+bo]="$(tput bold)"    [-bo]="$(tput sgr0)"
+    if [ $# -ge 1 ]; then
+        local fmtstr="$1"; shift
+        local -a args=( "${@}" ) #. XXX "${@}" to preserve array size in tokens with spaces
 
-    [bl]="$(tput setaf 0)"  [wh]="$(tput setaf 7)"
-    [r]="$(tput setaf 1)"   [g]="$(tput setaf 2)"
-    [y]="$(tput setaf 3)"   [b]="$(tput setaf 4)"
-    [m]="$(tput setaf 5)"   [c]="$(tput setaf 6)"
-)
+        local -a prefix
+        local fmtstr
+        local replacement
 
-function c() { core:raise EXCEPTION_DEPRECATED; }
+        while read arg; do
+            if [[ ${arg} =~ ^%\{([^:]+):([^}]*)}$ ]]; then
+                op=${BASH_REMATCH[1]}
+                token=${BASH_REMATCH[2]}
+                replacement="${token}"
 
+                #. Convert @theme to colorchar
+                case ${op} in
+                    !*) fmtstr=${fmtstr//${arg}/$(::cpf:theme "${op}" "${token}")};;
+                    @*)
+                        read _sym _fmt _arg <<< "$(::cpf:theme "${op}" "${token}")"
+                        [ "$_sym" != '0' ] || _sym=
+                        if [ ${SITE_IN_COLOR?} -eq 1 ]; then
+                            if ::cpf:is_fmt ${_fmt}; then
+                                prefix+=( "${_sym}" )
+                                #echo XXX _fmt $_fmt > /dev/stderr
+                                #echo XXX _arg $_arg > /dev/stderr
+                                #echo XXX _sym $_sym > /dev/stderr
+                                replacement=$(cpf "${_fmt}" "$_arg")
+                                #echo XXX replacement is now \"${replacement}\" > /dev/stderr
+                            else
+                                replacement=${_fmt}
+                            fi
+                            #echo XXX fmtstr="${fmtstr} minus ${arg} plus ${replacement}" > /dev/stderr
+                            fmtstr="${fmtstr//${arg}/${replacement}}"
+                        else
+                            replacement=${token}
+                            if ::cpf:is_fmt ${replacement}; then
+                                prefix+=( "${_sym}" )
+                            fi
+                            fmtstr="${fmtstr//${arg}/${replacement}}"
+                        fi
+                    ;;
+                    rv|bl|wh|r|g|y|b|m|c)
+                        if [ ${SITE_IN_COLOR?} -eq 1 ]; then
+                            #XXX echo xxxxxxxxxxxxx ${op} ${token} > /dev/stderr
+                            replacement="${COLORS[${op}]}${token}${COLORS[N]}"
+                        fi
+                        #XXX echo xxxxxxxxxxxxx replacing $arg with $replacement > /dev/stderr
+                        if ::cpf:is_fmt "${replacement}"; then
+                            prefix+=( "" )
+                        fi
+                        #XXX echo yyyyyyyyyyyyy ${fmtstr} > /dev/stderr
+                        fmtstr="${fmtstr//${arg}/${replacement}}"
+                        #XXX echo zzzzzzzzzzzzz ${fmtstr} > /dev/stderr
+                    ;;
+                    ul|st|bo)
+                        if [ ${SITE_IN_COLOR?} -eq 1 ]; then
+                            replacement="${COLORS[+${op}]}${token}${COLORS[-${op}]}"
+                        fi
+                        if ::cpf:is_fmt ${replacement}; then
+                            prefix+=( "" )
+                        fi
+                        fmtstr="${fmtstr//${arg}/${replacement}}"
+                    ;;
+                esac
+            elif [[ ${arg} =~ ^%\{([^:]+)}$ ]]; then
+                if [ ${SITE_IN_COLOR?} -eq 1 ]; then
+                    op="${BASH_REMATCH[1]}"
+                    replacement="${COLORS[${op}]}"
+                fi
+                prefix+=( "" )
+                fmtstr="${fmtstr//${arg}/${replacement}}"
+            fi
+        done < <(echo "${fmtstr}"|grep -oE '%{[^}]+}')
+
+        #echo "XXX fmt >>> ${fmtstr} <<<" > /dev/stderr
+        #echo "XXX arg ${#args[@]}: ${args[@]}" > /dev/stderr
+        #echo "XXX sym ${#prefix[@]}: ${prefix[@]}" > /dev/stderr
+        local -i substitutions=$(echo ${fmtstr}|sed -e 's/%{\([^}]*\)}/\1/g'|tr -c -d '%'|wc -c)
+        #echo "XXX [ ${substitutions} == ${#args[@]} ]" > /dev/stderr
+        if [ ${substitutions} -eq ${#args[@]} ]; then
+            if ! echo "${fmtstr}"|grep -qE '%{'; then
+                local -i i
+                for ((i=0; i<${#args[@]}; i++)); do
+                    #echo "XXX pre-change arg $i  >>> ${args[$i]}" > /dev/stderr
+                    args[${i}]="${prefix[$i]}${args[${i}]}"
+                    #echo "XXX post-chance arg $i >>> ${args[$i]}" > /dev/stderr
+                done
+                #. XXX
+                #echo format is "${fmtstr}" 2>/dev/stderr
+                #echo args are "${args[@]}" 2>/dev/stderr
+                printf "${fmtstr}" "${args[@]}"
+            else
+                echo "CPF Failure - still have %{ in the fmtstr!: ${fmtstr}" > /dev/stderr
+                exit 99
+            fi
+        else
+            echo "CPF Failure: mismatched arguments for given format string ( ${substitutions} in fmtstr, ${#args[@]} arguments supplied )" > /dev/stderr
+            echo "Formatstr: \`${fmtstr}'" > /dev/stderr
+            echo "Arguments:" > /dev/stderr
+            printf " * \`%s'\n" "${args[@]}" > /dev/stderr
+            #exit 99
+        fi
+    else
+        echo
+    fi
+
+    #echo "XXX FUNC RETN" > /dev/stderr
+}
+#. }=-
+#. theme -={
 function theme() {
     if [ $# -gt 0 ]; then
         local dvc=/dev/stdout
@@ -164,246 +398,18 @@ function theme() {
             ;;
         esac
 
-        if [ ${SITE_IN_COLOR} -eq 1 ]; then
+        if [ ${SITE_IN_COLOR?} -eq 1 ]; then
             cpf "${fmt}" "$@" >${dvc}
         else
             cpf "${fmt}" "$@"
         fi
     else
-        if [ ${SITE_IN_COLOR} -eq 1 ]; then
+        if [ ${SITE_IN_COLOR?} -eq 1 ]; then
             echo >${dvc}
         else
             echo
         fi
     fi
 }
-
-function ::cpf:module_is_modified() {
-    local -i e=9
-    local profile=$1
-    local module=$2
-    cd ${SITE_CORE}
-    if [ -e "${SITE_USER_MOD}/${module}" ]; then
-        local path=$(readlink "${SITE_USER_MOD}/${module}")
-        local amended=$(:core:git status --porcelain "${path}"|wc -l)
-        [ ${PIPESTATUS[0]} -ne 0 ] || e=${amended}
-    fi
-    #cd ${OLDPWD}
-
-    return $e
-}
-
-function ::cpf:module_has_alerts() {
-    local -i e=${CODE_FAILURE}
-
-    local profile=$1
-    local module=$2
-    if [ -e "${SITE_USER_MOD}/${module}" ]; then
-        grep -qE "^function ${module}:[a-z0-9]+:alert()" "${SITE_USER_MOD}/${module}"
-        [ $? -ne 0 ] || e=${CODE_SUCCESS}
-    fi
-
-    return $e
-}
-
-function ::cpf:function_has_alerts() {
-    local -i e=${CODE_FAILURE}
-
-    local profile=$1
-    local module=$2
-    local fn=$3
-    if [ -e "${SITE_USER_MOD}/${module}" ]; then
-        grep -qE "^function ${module}:${fn}:alert()" "${SITE_USER_MOD}/${module}"
-        [ $? -ne 0 ] || e=${CODE_SUCCESS}
-    fi
-
-    return $e
-}
-
-function ::cpf:module() {
-    local -r module=$1
-
-    local -i enabled=1
-    local -i alerts=0
-    local -i amended=0
-    local fmt
-    if [ -e ${SITE_CORE_MOD}/${module} ]; then
-        if ::cpf:module_has_alerts core ${module}; then
-            alerts=1
-            fmt="%{y}"
-        else
-            fmt="%{c}"
-            ::cpf:module_is_modified core ${module}
-            amended=$?
-        fi
-        enabled=${CORE_MODULES[${module}]}
-    elif [ -e ${SITE_USER_MOD}/${module} ]; then
-        if ::cpf:module_has_alerts ${SITE_PROFILE} ${module}; then
-            alerts=1
-            fmt="%{y}"
-        else
-            fmt="%{b}"
-            ::cpf:module_is_modified ${SITE_PROFILE} ${module}
-            amended=$?
-        fi
-        enabled=${USER_MODULES[${module}]}
-    fi
-
-    [ ${amended} -eq 0 ] || fmt+="%{ul}"
-    [ ${enabled} -eq 0 ] || fmt+="%{bo}"
-
-    cpf "${fmt}%s%{N}" ${module}
-}
-
-function ::cpf:function() {
-    local -r module=$1
-    local -r fn=$2
-
-    local -i enabled=1
-    local -i alerts=0
-    local -i amended=0
-    local fmt
-    if [ -e ${SITE_CORE_MOD}/${module} ]; then
-        if ::cpf:function_has_alerts core ${module} ${fn}; then
-            alerts=1
-            fmt="%{y}"
-        else
-            fmt="%{c}"
-            ::cpf:module_is_modified core ${module}
-            amended=$?
-        fi
-        enabled=${CORE_MODULES[${module}]}
-    elif [ -e ${SITE_USER_MOD}/${module} ]; then
-        if ::cpf:function_has_alerts ${SITE_PROFILE} ${module} ${fn}; then
-            alerts=1
-            fmt="%{y}"
-        else
-            fmt="%{b}"
-            ::cpf:module_is_modified ${SITE_PROFILE} ${module}
-            amended=$?
-        fi
-        enabled=${USER_MODULES[${module}]}
-    fi
-
-    [ ${amended} -eq 0 ] || fmt+="%{ul}"
-    [ ${enabled} -eq 0 ] || fmt+="%{bo}"
-
-    cpf "${fmt}%s %{b:%s}%{N}" ${module} ${fn}
-}
-
-#. Main Public Function -={
-function cpf() {
-    #. cpf "%{ul:%s}, %{r}%{bo:%s}, and %{st:%s}%{no}\n" underlined bold standard
-    LC_ALL=C
-
-    #echo "XXX FUNC CALL with ${#}" > /dev/stderr
-
-    if [ $# -ge 1 ]; then
-        local fmtstr="$1"; shift
-        local -a args=( "${@}" ) #. XXX "${@}" to preserve array size in tokens with spaces
-
-        local -a prefix
-        local fmtstr
-        local replacement
-
-        while read arg; do
-            if [[ ${arg} =~ ^%\{([^:]+):([^}]*)}$ ]]; then
-                op=${BASH_REMATCH[1]}
-                token=${BASH_REMATCH[2]}
-                replacement="${token}"
-
-                #. Convert @theme to colorchar
-                case ${op} in
-                    !*) fmtstr=${fmtstr//${arg}/$(::cpf:theme "${op}" "${token}")};;
-                    @*)
-                        read _sym _fmt _arg <<< "$(::cpf:theme "${op}" "${token}")"
-                        [ "$_sym" != '0' ] || _sym=
-                        if [ ${SITE_IN_COLOR} -eq 1 ]; then
-                            if is_fmt ${_fmt}; then
-                                prefix+=( "${_sym}" )
-                                #echo XXX _fmt $_fmt > /dev/stderr
-                                #echo XXX _arg $_arg > /dev/stderr
-                                #echo XXX _sym $_sym > /dev/stderr
-                                replacement=$(cpf "${_fmt}" "$_arg")
-                                #echo XXX replacement is now \"${replacement}\" > /dev/stderr
-                            else
-                                replacement=${_fmt}
-                            fi
-                            #echo XXX fmtstr="${fmtstr} minus ${arg} plus ${replacement}" > /dev/stderr
-                            fmtstr="${fmtstr//${arg}/${replacement}}"
-                        else
-                            replacement=${token}
-                            if is_fmt ${replacement}; then
-                                prefix+=( "${_sym}" )
-                            fi
-                            fmtstr="${fmtstr//${arg}/${replacement}}"
-                        fi
-                    ;;
-                    rv|bl|wh|r|g|y|b|m|c)
-                        if [ ${SITE_IN_COLOR} -eq 1 ]; then
-                            #XXX echo xxxxxxxxxxxxx ${op} ${token} > /dev/stderr
-                            replacement="${COLORS[${op}]}${token}${COLORS[N]}"
-                        fi
-                        #XXX echo xxxxxxxxxxxxx replacing $arg with $replacement > /dev/stderr
-                        if is_fmt "${replacement}"; then
-                            prefix+=( "" )
-                        fi
-                        #XXX echo yyyyyyyyyyyyy ${fmtstr} > /dev/stderr
-                        fmtstr="${fmtstr//${arg}/${replacement}}"
-                        #XXX echo zzzzzzzzzzzzz ${fmtstr} > /dev/stderr
-                    ;;
-                    ul|st|bo)
-                        if [ ${SITE_IN_COLOR} -eq 1 ]; then
-                            replacement="${COLORS[+${op}]}${token}${COLORS[-${op}]}"
-                        fi
-                        if is_fmt ${replacement}; then
-                            prefix+=( "" )
-                        fi
-                        fmtstr="${fmtstr//${arg}/${replacement}}"
-                    ;;
-                esac
-            elif [[ ${arg} =~ ^%\{([^:]+)}$ ]]; then
-                if [ ${SITE_IN_COLOR} -eq 1 ]; then
-                    op="${BASH_REMATCH[1]}"
-                    replacement="${COLORS[${op}]}"
-                fi
-                prefix+=( "" )
-                fmtstr="${fmtstr//${arg}/${replacement}}"
-            fi
-        done < <(echo "${fmtstr}"|grep -oE '%{[^}]+}')
-
-        #echo "XXX fmt >>> ${fmtstr} <<<" > /dev/stderr
-        #echo "XXX arg ${#args[@]}: ${args[@]}" > /dev/stderr
-        #echo "XXX sym ${#prefix[@]}: ${prefix[@]}" > /dev/stderr
-        local -i substitutions=$(echo ${fmtstr}|sed -e 's/%{\([^}]*\)}/\1/g'|tr -c -d '%'|wc -c)
-        #echo "XXX [ ${substitutions} == ${#args[@]} ]" > /dev/stderr
-        if [ ${substitutions} -eq ${#args[@]} ]; then
-            if ! echo "${fmtstr}"|grep -qE '%{'; then
-                local -i i
-                for ((i=0; i<${#args[@]}; i++)); do
-                    #echo "XXX pre-change arg $i  >>> ${args[$i]}" > /dev/stderr
-                    args[${i}]="${prefix[$i]}${args[${i}]}"
-                    #echo "XXX post-chance arg $i >>> ${args[$i]}" > /dev/stderr
-                done
-                #. XXX
-                #echo format is "${fmtstr}" 2>/dev/stderr
-                #echo args are "${args[@]}" 2>/dev/stderr
-                printf "${fmtstr}" "${args[@]}"
-            else
-                echo "CPF Failure - still have %{ in the fmtstr!: ${fmtstr}" > /dev/stderr
-                exit 99
-            fi
-        else
-            echo "CPF Failure: mismatched arguments for given format string ( ${substitutions} in fmtstr, ${#args[@]} arguments supplied )" > /dev/stderr
-            echo "Formatstr: \`${fmtstr}'" > /dev/stderr
-            echo "Arguments:" > /dev/stderr
-            printf " * \`%s'\n" "${args[@]}" > /dev/stderr
-            #exit 99
-        fi
-    else
-        echo
-    fi
-
-    #echo "XXX FUNC RETN" > /dev/stderr
-}
+#. }=-
 #. }=-
