Fixed `module/hgd': closes nima/site#3
Updated `module/hgd': hgd reqirement: one entry per line.
Specifically, the mongo results have been reverted to one per line.

Also fixed error checking on the return of the sets script.

diff --git a/module/hgd b/module/hgd
--- a/module/hgd
+++ b/module/hgd
@@ -55,10 +55,10 @@ function ::hgd:explode() {
                 fi
             ;;
             '%')
-                local -a hosts
+                local -a filters
                 IFS=% read -a filters <<< "${hgdn}"
-                hosts=( $(:mongo:query ${PROFILE//@*} qdn ${filters[@]}) )
-                echo ${hosts[@]}
+                local -a hosts
+                :mongo:query ${PROFILE//@*} qdn ${filters[@]}
                 [ $? -eq ${CODE_SUCCESS} ] || e=${CODE_FAILURE}
             ;;
             '#')
@@ -113,23 +113,24 @@ function ::hgd:resolve() {
     local -A buffers
 
     if [ $# -eq 2 ]; then
-        e=${CODE_SUCCESS}
-
         local tldid=$1
         local eq="$2"
-        read -a hgds <<< $(${SITE_LIBEXEC_CORE}/sets "${eq}")
-
-        local buf;
-        for hgd in ${hgds[@]}; do
-            buf="$(::hgd:explode ${tldid} ${hgd})"
-            if [ $? -eq 0 ]; then
-                buffers[${hgd}]="${buf}"
-            else
-                theme ERR "Failed to resolve ${hgd}"
-                e=${CODE_FAILURE}
-                break
-            fi
-        done
+        local buf
+        buf=$(${SITE_LIBEXEC_CORE}/sets "${eq}")
+        if [ $? -eq 0 ]; then
+            e=${CODE_SUCCESS}
+            read -a hgds <<< "${buf}"
+            for hgd in ${hgds[@]}; do
+                buf="$(::hgd:explode ${tldid} ${hgd})"
+                if [ $? -eq 0 ]; then
+                    buffers[${hgd}]="${buf}"
+                else
+                    theme ERR "Failed to resolve ${hgd}"
+                    e=${CODE_FAILURE}
+                    break
+                fi
+            done
+        fi
     fi
 
     if [ $e -eq ${CODE_SUCCESS} ]; then
@@ -164,7 +165,7 @@ function :hgd:resolve() {
         elif [[ ${2:0:1} =~ ^[a-zA-Z0-9]$ ]]; then
             local session="$2"
             local -a buflist
-            buflist=( $(awk -F '\t' '$1~/^'${session}'$/&&$2~/^'${tldid}'$/{print$0}' ${g_HGD_CACHE}) )
+            buflist=( $(awk -F '\t' '$1~/^'${session}'$/&&$2~/^('${tldid}'|\.)$/{print$0}' ${g_HGD_CACHE}) )
             if [ $? -eq ${CODE_SUCCESS} -a ${#buflist[@]} -gt 3 ]; then
                 e=${CODE_SUCCESS}
                 echo ${buflist[@]:4}
@@ -241,7 +242,7 @@ function :hgd:save() {
         if [ $? -eq 0 -a ${#hosts[@]} -gt 0 ]; then
             :hgd:delete ${session}
         fi
-        echo -ne "${session}\t${tldid}\t${NOW}\t${hgd}\t${hosts[@]}\n" >> ${g_HGD_CACHE}
+        echo -ne "${session}\t${tldid}\t${NOW}\t${hgd}\t${hosts[@]}\n" >> ${g_HGD_CACHE?}
         e=${CODE_SUCCESS}
     else
         core:raise EXCEPTION_BAD_FN_CALL "$# arguments given, 2 expected"
@@ -297,23 +298,24 @@ function :hgd:list() {
 function hgd:list() {
     local -i e=${CODE_DEFAULT?}
 
-    if [ $# -eq 0 -o $# -eq 1 ]; then
-        local data
-        data="$(:hgd:list $@)"
-        e=$?
-        case $e in
-            ${CODE_SUCCESS})
-                while read line; do
-                    read -a data <<< "$line"
-                    cpf '%{y:%-24s} %{@tldid:%s} %{@int:%3s} %{bl:%s} %{@hgd:%s}\n'\
-                        ${data[0]} ${data[1]} $((${#data[@]}-4)) $(:util:date:i2s ${data[2]}) ${data[3]}
-                done <<< "${data}"
-            ;;
-            2) theme HAS_FAILED "You have no saved sessions by that name"; e=${CODE_FAILURE};;
-            3) theme HAS_WARNED "You have no saved sessions"; e=${CODE_SUCCESS};;
-            *) core:raise EXCEPTION_UNHANDLED;;
-        esac
-    fi
+    local data
+    data=$(:hgd:list "$@")
+    e=$?
+    case $#:$e in
+        0:${CODE_SUCCESS}|1:${CODE_SUCCESS})
+            while read line; do
+                read -a data <<< "$line"
+                cpf '%{y:%-24s} %{@tldid:%s} %{@int:%3s} %{bl:%s} %{@hgd:%s}\n'\
+                    ${data[0]} ${data[1]} $((${#data[@]}-4)) $(:util:date:i2s ${data[2]}) ${data[3]}
+            done <<< "${data}"
+        ;;
+        0:2) theme HAS_WARNED "You have no saved sessions"; e=${CODE_SUCCESS};;
+        1:3) theme HAS_FAILED "You have no saved sessions by that name"; e=${CODE_FAILURE};;
+        *)
+            theme EXCEPTION "$#:$e is unhandled."
+            core:raise EXCEPTION_UNHANDLED
+        ;;
+    esac
 
     return $e
 }
@@ -325,7 +327,7 @@ function :hgd:load() {
     if [ $# -eq 2 ]; then
         local tldid=$1
         local session=$2
-        local hgd=$(awk -F '\t' '$1~/^'${session}'$/&&$2~/^'${tldid}'$/{print$4}' ${g_HGD_CACHE})
+        local hgd=$(awk -F '\t' '$1~/^'${session}'$/&&$2~/^('${tldid}'|\.)$/{print$4}' ${g_HGD_CACHE})
         if [ ${#hgd} -gt 0 ]; then
             echo ${hgd}
             e=${CODE_SUCCESS}
