Updated `lib/core/ldap': rename, fix, new
New test for verification netgroups nisNetgroupTriple tuples, to
check for correct, warning, and erroneous data (Josh Roberts).

The `ping' function is now called `checksum', and taks an optional
list of two or more indexes into the configured LDAP hosts array,
which is a site-specific configuration.

This function now also compares netgroups (rather than just users),
however there is some serious hard-coding going on at the moment.

Fixed a bug with the public ldap search which would only return one
entry; now it returns all matches, separated by blank lines.

diff --git a/lib/core/ldap b/lib/core/ldap
--- a/lib/core/ldap
+++ b/lib/core/ldap
@@ -326,37 +326,58 @@ function ldap:ngldif() {
     return $e
 }
 
-function ldap:ping:usage() { echo " "; }
-function ldap:ping() {
+function ldap:checksum:usage() { echo "[<ldaphostid> <ldaphostid> [<ldaphostid> [...]]]"; }
+function ldap:checksum() {
     core:requires ANY colordiff diff
 
     local -i e=${CODE_DEFAULT}
 
+    local lhi
+    local -a ldaphostids
     if [ $# -eq 0 ]; then
         local -i e=${CODE_SUCCESS}
+        ldaphostids=( ${!USER_LDAPHOSTS[@]} )
+    elif [ $# -ge 2 ]; then
+        local -i e=${CODE_SUCCESS}
+        for lhi in $@; do
+            if [ ${lhi} -lt ${#USER_LDAPHOSTS[@]} ]; then
+                ldaphostids+=( ${lhi} )
+            else
+                local -i e=${CODE_FAILURE}
+            fi
+        done
+    fi
 
-        local -A sync
-        local -A sync_code
+    if [ $e -eq ${CODE_SUCCESS} ]; then
         local -A dump
         local md5
         local uidc
-        for uidc in {a..z}; do
 
-            cpf "Integrity check for %{c:uid=}%{r:${uidc}*}..."
+        local -a ldaphosts
+        for lhi in ${ldaphostids[@]}; do
+            ldaphosts+=( ${USER_LDAPHOSTS[${lhi}]} )
+        done
+        cpf "Integrity check between %{@int:%s} ldap hosts (ids:%{@int:%s})...\n"\
+            "${#ldaphostids[@]}" "$(:util:join , ldaphostids)"
+
+        for ngc in {a..z}; do
+            cpf "Integrity check for %{c:ng=}%{r:${ngc}*}..."
             local -A md5s=()
-            for lh in ${USER_LDAPHOSTS[@]}; do
+            for lh in ${ldaphosts[@]}; do
                 dump[${lh}]=$(
-                    ldapsearch -x -LLL -E pr=128/noprompt -S dn -h "${lh}" -b "${USER_UDN}"\
-                        uid="${uidc}*" ${USER_LDAP_SYNC_ATTRS[@]} |
+                    ldapsearch -x -LLL -E pr=128/noprompt -S dn -h "${lh}" -b "${USER_NDN}"\
+                        cn="${ngc}*" cn memberNisNetgroup netgroupTriple description |
                             sed -e 's/^dn:.*/\L&/' |
                             grep -v 'pagedresults:' 2>/dev/null
                 )
-                [ $? -eq 0 ] && cpf '.' || cpf '!'
+                [ $? -eq 0 ] && cpf '+' || cpf '!'
                 md5="$(echo ${dump[${lh}]}|md5sum|awk '{print$1}')"
                 md5s[${md5}]=${lh}
             done
 
-            local ldaphost=$(:ldap:host)
+            #. identical block -={
+            cpf ...
+            local ldaphost=${ldaphosts[0]}
             local -i len=$(echo "${dump[${ldaphost}]}"|wc -c)
             if [ ${#md5s[@]} -eq 1 ]; then
                 if [ ${len} -gt 1 ]; then
@@ -365,18 +386,58 @@ function ldap:ping() {
                     theme HAS_WARNED ${md5}:${len}
                 fi
             else
-                theme HAS_FAILED "${#md5s[@]} variants in the ${#USER_LDAPHOSTS[@]} hosts"
+                theme HAS_FAILED "${#md5s[@]} variants in the ${#ldaphosts[@]} hosts"
                 e=${CODE_FAILURE}
-                for lh in ${USER_LDAPHOSTS[@]}; do
+                for lh in ${ldaphosts[@]}; do
                     if [ ${lh} != ${ldaphost} ]; then
                         cpf "%{@host:${ldaphost}} vs %{@host:${lh}}...\n"
-                        #colordiff -y -a \
-                        colordiff -T -a -U3 \
-                            <(echo "${dump[${ldaphost}]}") \
+                        ${SITE_DIFF} -T -a -U3\
+                            <(echo "${dump[${ldaphost}]}")\
                             <(echo "${dump[${lh}]}")
                     fi
                 done
             fi
+            #. }=-
+        done
+
+        for uidc in {a..z}; do
+            cpf "Integrity check for %{c:uid=}%{r:${uidc}*}..."
+            local -A md5s=()
+            for lh in ${ldaphosts[@]}; do
+                dump[${lh}]=$(
+                    ldapsearch -x -LLL -E pr=128/noprompt -S dn -h "${lh}" -b "${USER_UDN}"\
+                        uid="${uidc}*" ${USER_LDAP_SYNC_ATTRS[@]} |
+                            sed -e 's/^dn:.*/\L&/' |
+                            grep -v 'pagedresults:' 2>/dev/null
+                )
+                [ $? -eq 0 ] && cpf '+' || cpf '!'
+                md5="$(echo ${dump[${lh}]}|md5sum|awk '{print$1}')"
+                md5s[${md5}]=${lh}
+            done
+
+            #. identical block -={
+            cpf ...
+            local ldaphost=${ldaphosts[0]}
+            local -i len=$(echo "${dump[${ldaphost}]}"|wc -c)
+            if [ ${#md5s[@]} -eq 1 ]; then
+                if [ ${len} -gt 1 ]; then
+                    theme HAS_PASSED ${md5}:${len}
+                else
+                    theme HAS_WARNED ${md5}:${len}
+                fi
+            else
+                theme HAS_FAILED "${#md5s[@]} variants in the ${#ldaphosts[@]} hosts"
+                e=${CODE_FAILURE}
+                for lh in ${ldaphosts[@]}; do
+                    if [ ${lh} != ${ldaphost} ]; then
+                        cpf "%{@host:${ldaphost}} vs %{@host:${lh}}...\n"
+                        ${SITE_DIFF} -T -a -U3\
+                            <(echo "${dump[${ldaphost}]}")\
+                            <(echo "${dump[${lh}]}")
+                    fi
+                done
+            fi
+            #. }=-
         done
 
     fi
@@ -588,7 +649,7 @@ function ldap:search() {
                 local -a filter
                 local -a display
                 local token
-                for token in ${@:3}; do
+                for token in ${@:2}; do
                     if [[ ${token} =~ [-a-zA-Z0-9_]+([~\<\>]?=).+ ]]; then
                         filter+=( "(${token})" )
                     else
@@ -600,18 +661,60 @@ function ldap:search() {
                     fi
                 done
 
-                IFS="${SITE_DELIM}" read ${display[@]} <<< "${data}"
+                while IFS="${SITE_DELIM}" read ${display[@]}; do
+                    for attr in ${display[@]}; do
+                        local value=${!attr}
+                        if [ ${#value} -gt 0 ]; then
+                            cpf "%{@key:%-32s}%{@val:%s}\n" "${attr}" "${value}"
+                        else
+                            cpf "%{@key:%-32s}%{@err:%s}\n" "${attr}" "ERROR"
+                            e=${CODE_FAILURE}
+                        fi
+                    done
+                    cpf
+                done <<< "${data}"
+            else
+                theme HAS_FAILED "UNKNOWN ERROR"
+            fi
+        fi
+    fi
 
-                for attr in ${display[@]}; do
-                    local value=${!attr}
-                    if [ ${#value} -gt 0 ]; then
-                        cpf "%{@key:%-32s}%{@val:%s}\n" "${attr}" "${value}"
+    return $e
+}
+
+function ldap:ngverify() {
+    #. NOTE
+    #. If any of the specified attributes are missing, every attribute will
+    #. fail.  This can be fixed, but at relatively great expense as each
+    #. attribute will result in a dedicated ldap query.
+
+    local -i e=${CODE_DEFAULT?}
+
+    if [ $# -eq 0 ]; then
+        local bdn=${USER_NDN}
+        local data=$(:ldap:search -2 netgroup cn nisNetgroupTriple)
+        e=$?
+        if [ ${e} -eq ${CODE_SUCCESS} ]; then
+            #. Look for filter tokens
+            while IFS="${SITE_DELIM}" read cn nisNetgroupTripleRaw; do
+                local -i hits=0
+                IFS='|||' read -a nisNetgroupTriples <<< "${nisNetgroupTripleRaw}"
+                for nisNetgroupTriple in ${nisNetgroupTriples[@]}; do
+                    if [[ ${nisNetgroupTriple} =~ ${USER_REGEX[NIS_NETGROUP_TRIPLE_PASS]} ]]; then
+                        : cpf "%{@netgroup:%-32s} -> %{@pass:%s}\n" ${cn} ${nisNetgroupTriple}
+                        : hits=1
+                    elif [[ ${nisNetgroupTriple} =~ ${USER_REGEX[NIS_NETGROUP_TRIPLE_WARN]} ]]; then
+                        cpf "%{@netgroup:%-32s} -> %{@warn:%s}\n" ${cn} ${nisNetgroupTriple}
+                        hits=1
                     else
-                        cpf "%{@key:%-32s}%{@err:%s}\n" "${attr}" "ERROR"
-                        e=${CODE_FAILURE}
+                        cpf "%{@netgroup:%-32s} -> %{@fail:%s}\n" ${cn} ${nisNetgroupTriple}
+                        hits=1
                     fi
                 done
-            fi
+                [ ${hits} -eq 0 ] || cpf
+            done <<< "${data}"
+        else
+            theme HAS_FAILED "LDAP_CONNECT"
         fi
     fi
 
