Overhauled `site:core:ldap': rewrite, secrets
Trying to clean up what is there before adding too much more
functionality.

Updated an old experimental bit of code that used a similar secrets
script, now replaced with a utility function which does the same thing
effectively, but in line with the framework.

diff --git a/lib/core/ldap b/lib/core/ldap
--- a/lib/core/ldap
+++ b/lib/core/ldap
@@ -7,11 +7,10 @@ core:import util
 declare -g g_PASSWD_CACHED=
 function :ldap:authenticate() {
     local -i e=${CODE_FAILURE}
+
     if [ ${#g_PASSWD_CACHED} -eq 0 ]; then
-        if which secret >/dev/null 2>&1; then
-            g_PASSWD_CACHED=$(secret LDAP)
-            e=$?
-        fi
+        g_PASSWD_CACHED="$(:util:secrets LDAP)"
+        e=$?
 
         if [ $e -ne 0 ]; then
             read -p "Enter LDAP (${USER_LDAPHOST_RW}) Password: " -s g_PASSWD_CACHED
@@ -40,51 +39,80 @@ function :ldap:authenticate() {
 #. 19  - LDAP_CONSTRAINT_VIOLATION
 #. 20  - LDAP_TYPE_OR_VALUE_EXISTS
 
-function ::ldap:modify() {
-    local username=$1
-    echo "# vim:syntax=ldif"
-    echo "dn: uid=${username},${USER_UDN}"
-    echo "changetype: modify"
+function ldap:mkldif:usage() { echo "add|modify|replace|delete user|group <username>/<groupname> <attr1> <val1> [<val2> [...]] [- <attr2> ...]"; }
+function ldap:mkldif() {
+    local -i e=${CODE_DEFAULT}
 
-    local attr=
-    for ((i=4; i<$#+1; i++)); do
-        if [ "${!i}" != "-" -a ${#attr} -gt 0 ]; then
-            printf "\n${attr}: ${!i}";
-        else
-            if [ ${#attr} -gt 0 ]; then
-                printf "\n-\n"
-                ((i++))
-            fi
-            attr=${!i}
-            printf "${change}: ${attr}"
-        fi
-    done;
-    printf "\n "
+    if [ $# -ge 4 ]; then
+        ::ldap:mkldif $@
+        e=$?
+    fi
+
+    return $e
 }
-function :ldap:modify() {
+function ::ldap:mkldif() {
+: <<!
+    This function generates an ldif; which is suitable for feeding into
+    ldapmodify.
+!
     local -i e=${CODE_FAILURE}
 
-    if [ $# -ge 2 ]; then
-        local context=$1
+    if [ $# -gt 3 ]; then
+        local action=$1
+        local context=$2
+
+        local -A changes=(
+            [modify]=modify
+            [add]=modify
+            [replace]=modify
+            [delete]=delete
+        )
+        local change=${changes[${action}]}
+
         case $context in
             user)
-                local username=$2
-                local change=$3
-                if :ldap:authenticate; then
-                    case ${change} in
-                        delete|add|replace)
-                            shift
-                            local ldif="$(::ldap:modify ${username} ${@})"
-                            ldapmodify -x -h ${USER_LDAPHOST_RW} -D "uid=${USER_USERNAME},${USER_UDN}" -w "${g_PASSWD_CACHED}" -c <<< "${ldif}"  >/dev/null 2>&1
-                            e=$?
-                            if [ $e -ne ${CODE_SUCCESS} ]; then
-                                cpf "%{@comment:#. } LDIF %{@err:Failed} with status code %{@int:$e}:\n" >&2
-                                ${SITE_LIB_EXTERN}/vimcat <<< "${ldif}" >&2
-                            fi
-                        ;;
-                        *) core:raise EXCEPTION_BAD_FN_CALL;;
-                    esac
-                fi
+                local username=$3
+                echo "# vim:syntax=ldif"
+                echo "dn: uid=${username},${USER_UDN}"
+                echo "changetype: ${change}"
+
+                local attr=
+                for ((i=4; i<$#+1; i++)); do
+                    if [ "${!i}" != "-" -a ${#attr} -gt 0 ]; then
+                        printf "\n${attr}: ${!i}";
+                    else
+                        if [ ${#attr} -gt 0 ]; then
+                            printf "\n-\n"
+                            ((i++))
+                        fi
+                        attr=${!i}
+                        printf "${action}: ${attr}"
+                    fi
+                done;
+                printf "\n "
+                e=${CODE_SUCCESS}
+            ;;
+            group)
+                local groupname=$3
+                echo "# vim:syntax=ldif"
+                echo "dn: cn=${groupname},${USER_GDN}"
+                echo "changetype: ${change}"
+
+                local attr=
+                for ((i=4; i<$#+1; i++)); do
+                    if [ "${!i}" != "-" -a ${#attr} -gt 0 ]; then
+                        printf "\n${attr}: ${!i}";
+                    else
+                        if [ ${#attr} -gt 0 ]; then
+                            printf "\n-\n"
+                            ((i++))
+                        fi
+                        attr=${!i}
+                        printf "${action}: ${attr}"
+                    fi
+                done;
+                printf "\n "
+                e=${CODE_SUCCESS}
             ;;
             *) core:raise EXCEPTION_BAD_FN_CALL;;
         esac
@@ -95,7 +123,64 @@ function :ldap:modify() {
     return $e
 }
 
+function :ldap:modify() {
+    local -i e=${CODE_FAILURE}
+
+    if [ $# -ge 3 ]; then
+        local context=$1
+        case ${context} in
+            user)
+                if :ldap:authenticate; then
+                    local username=$2
+                    local change=$3
+                    case ${change} in
+                        delete|add|replace)
+                            shift 3
+                            local ldif="$(::ldap:mkldif ${change} user ${username} ${@})"
+                            ldapmodify -x -h ${USER_LDAPHOST_RW} -D "uid=${USER_USERNAME},${USER_UDN}" -w "${g_PASSWD_CACHED}" -c <<< "${ldif}"  >/dev/null 2>&1
+                            e=$?
+                            if [ $e -ne ${CODE_SUCCESS} ]; then
+                                cpf "%{@comment:#. } LDIF %{@err:Failed} with status code %{@int:$e}:\n" >&2
+                                ${SITE_LIB_EXTERN}/vimcat <<< "${ldif}" >&2
+                            fi
+                        ;;
+                        *) core:raise EXCEPTION_BAD_FN_CALL INVALID_USER_CHANGE;;
+                    esac
+                fi
+            ;;
+            group)
+                if :ldap:authenticate; then
+                    local groupname=$2
+                    local change=$3
+                    case ${change} in
+                        modify|delete|add|replace)
+                            shift 3
+                            local ldif="$(::ldap:mkldif ${change} group ${groupname} ${@})"
+                            ldapmodify -x -h ${USER_LDAPHOST_RW} -D "uid=${USER_USERNAME},${USER_UDN}" -w "${g_PASSWD_CACHED}" -c <<< "${ldif}"  >/dev/null 2>&1
+                            e=$?
+                            if [ $e -ne ${CODE_SUCCESS} ]; then
+                                cpf "%{@comment:#. } LDIF %{@err:Failed} with status code %{@int:$e}:\n" >&2
+                                ${SITE_LIB_EXTERN}/vimcat <<< "${ldif}" >&2
+                            fi
+                        ;;
+                        *) core:raise EXCEPTION_BAD_FN_CALL INVALID_GROUP_CHANGE;;
+                    esac
+                fi
+            ;;
+            *) core:raise EXCEPTION_BAD_FN_CALL INVALID_CONTEXT;;
+        esac
+    else
+        core:raise EXCEPTION_BAD_FN_CALL INVALID_FN_CALL
+    fi
+
+    return $e
+}
+
 function :ldap:add() {
+: <<!
+    This function looks at defined _ldap_* variables and performs an ldapadd
+    (ldapmodify -a).
+!
     local -i e=${CODE_FAILURE}
 
     if [ $# -eq 1 ]; then
@@ -103,14 +188,16 @@ function :ldap:add() {
             local context=$1
             case $context in
                 user)
-                    ldapadd -x -h ${USER_LDAPHOST_RW} -D "uid=${USER_USERNAME},${USER_UDN}" -w "${g_PASSWD_CACHED}" -f <(
+                    ldapmodify -a -x -h ${USER_LDAPHOST_RW} -D "uid=${USER_USERNAME},${USER_UDN}" -w "${g_PASSWD_CACHED}" -f <(
                         echo "dn: uid=${dstuid},${USER_UDN}"
                         unset _ldap_dn
                         for attrs in ${!_ldap_*}; do
                             local -i i
-                            local -i attrlen=$(eval "echo \${#$attrs[@]}") #. number of attribute definitions
+                            #. number of attribute definitions
+                            local -i attrlen=$(eval "echo \${#$attrs[@]}")
                             for ((i=0; i<${attrlen}; i++)); do
-                                eval 'echo "${attrs//_ldap_/}: ${'$attrs'[${i}]}"' | sed -e 's/\<'${srcuid}'\>/'${dstuid}'/g'
+                                eval 'echo "${attrs//_ldap_/}: ${'$attrs'[${i}]}"' |
+                                    sed -e 's/\<'${srcuid}'\>/'${dstuid}'/g'
                             done
                         done
                         echo
@@ -224,7 +311,7 @@ function :ldap:eval:search() {
         case $context in
             user)
                 local userdata=$(
-                    ldapsearch -x -LLL -E pr=1024/noprompt -h "${USER_LDAPHOST}" -b "${USER_UDN}" "uid=${username}" ${@}
+                    ldapsearch -x -LLL -E pr=1024/noprompt -h "${USER_LDAPHOST}" -b "${USER_UDN}" "uid=${username}" ${@}|grep -vE ^#
                 )
                 if [ $# -gt 0 ]; then
                     #. User specified which attrs they want:
@@ -323,7 +410,7 @@ function :ldap:search() {
 
             local awkfields='$4'
             for ((i=6; i<=${awknf}; i+=2)); do
-                awkfields+=",\"+++\",\$$i"
+                awkfields+=",\"${SITE_DELIM}\",\$$i"
             done
 
             #. Script-readable dump
@@ -333,7 +420,7 @@ function :ldap:search() {
             #cpf "%{@cmd:%s}\n" "${querystr}"
 
             #. TITLE: echo ${display[@]^^}
-            eval ${querystr} | awk -v displaystr=${displaystr} '
+            eval ${querystr} | grep -vE '^#' | awk -v displaystr=${displaystr} '
 BEGIN{
     FS="\n";
     RS="\n\n";
@@ -352,7 +439,7 @@ BEGIN{
 
     if(data[key]) {
         for(i=1; i<=length(display); i++) {
-            if(i>1) printf("+++");
+            if(i>1) printf("'${SITE_DELIM?}'");
             key = display[i];
             printf("%s", data[key]);
         }
@@ -369,7 +456,7 @@ BEGIN{
     return $e
 }
 
-function ldap:search:usage() { echo "user|group|netgroup <filters> <show-fields>"; }
+function ldap:search:usage() { echo "user|group|netgroup <filters>/<show-fields>"; }
 function ldap:search() {
     local -i e=${CODE_DEFAULT?}
 
@@ -384,7 +471,7 @@ function ldap:search() {
 
         if [ ${#bdn} -gt 0 ]; then
             :ldap:search $@
-            e=${PIPESTATUS[0]}
+            e=$?
         fi
     fi
 
