Overhauled `site:core:ssh': proxy, scp, fix, cleanup
New:

    Implemented scp as `:ssh:copy()'

    Now able to connect to specified interface rather than defaulting
    to one.  That means that many functions will now need to specify
    which interface (via tldid) they want to connect through.

    Use the new ${tldid} and associative array configuration variable
    for identifying which interface to connect to.

    SSH timeout is now user-defined.

Cleanup:

    Variable names cleaned up, and some bug fixes on how some
    where used.

diff --git a/lib/core/ssh b/lib/core/ssh
--- a/lib/core/ssh
+++ b/lib/core/ssh
@@ -4,18 +4,75 @@ core:import dns
 core:import hgd
 core:import util
 
+declare -g g_SSH_OPT
+g_SSH_OPTS="-q -o ConnectionAttempts=${USER_SSH_ATTEMPTS:-2} -o ConnectTimeout=${USER_SSH_TIMEOUT:-3} -o PasswordAuthentication=no"
+
+function :ssh:copy() {
+# FIXME - if fqdn is sent, work out tldid backwards?
+    local -i e=${CODE_FAILURE?}
+
+    #.Usage: :ssh:copy ${fqdn}:/etc/security/access.conf ${SITE_CACHE}/${fqdn}-access.conf
+    if [ $# -eq 3 ]; then
+        local tldid=$1
+        local qdn=$2
+        shift 2
+
+        local ssh_proxy=${USER_SSH_PROXY[${tldid}]}
+        local scp_opts="${g_SSH_OPTS}"
+        if [ ${#ssh_proxy} -eq 0 ]; then
+            scp ${scp_opts} ${SITE_USERNAME}@${qdn} $*
+        else
+            #. FIXME: Hardcoding m...
+            scp ${scp_opts} -o ProxyCommand="ssh ${SITE_USERNAME}@${ssh_proxy}\
+                nc %h.${USER_TLDS[${tldid}]} 22" ${SITE_USERNAME}@${qdn} $*
+        fi
+    fi
+
+    return $e
+}
+
 function :ssh:connect() {
     local -i e=${CODE_FAILURE?}
 
-    local SSH_OPTS='-q -o ConnectionAttempts=1 -o ConnectTimeout=1 -o PasswordAuthentication=no'
-    if [ $# -eq 1 ]; then
-        ssh -t ${SSH_OPTS} $*
-        e=$?
-    elif [ $# -ge 2 ]; then
-        ssh -T ${SSH_OPTS} $*
-        e=$?
+    if [ $# -ge 2 ]; then
+        local tldid=$1
+        local hnh=$2
+        shift 2
+
+        if [ ${#USER_IFACE[${tldid}]} -gt 0 ]; then
+            local -a qdns=( $(:dns:qdn ${tldid} ${hnh}) )
+            if [ ${#qdns[@]} -gt 0 ]; then
+                local qdn=${qdns[0]}
+
+                local ssh_opts
+                if [ $# -eq 0 ]; then
+                    #. User wants to ssh into a shell
+                    ssh_opts="${g_SSH_OPTS} -t"
+                elif [ $# -ge 1 ]; then
+                    #. User wants to ssh and execute a command
+                    ssh_opts="${g_SSH_OPTS} -T"
+                else
+                    #. User is confused, and so will we be.
+                    core:raise EXCEPTION_BAD_FN_CALL
+                fi
+
+                local ssh_proxy=${USER_SSH_PROXY[${tldid}]}
+                if [ ${#ssh_proxy} -eq 0 ]; then
+                    ssh ${ssh_opts} ${SITE_USERNAME}@${qdn} $*
+                    e=$?
+                else
+                    ssh ${ssh_opts} -o ProxyCommand="ssh ${SITE_USERNAME}@${ssh_proxy}\
+                        nc %h.${USER_TLDS[${tldid}]} 22" ${SITE_USERNAME}@${qdn} $*
+                    e=$?
+                fi
+            else
+                core:raise EXCEPTION_BAD_FN_CALL "No such host"
+            fi
+        else
+            core:raise EXCEPTION_BAD_FN_CALL "Invalid TLDID"
+        fi
     else
-        core:raise ${EXCEPTION_BAD_FN_CALL}
+        core:raise EXCEPTION_BAD_FN_CALL
     fi
 
     return $e
@@ -50,17 +107,33 @@ function :ssh:sudo() {
         local passwd
         passwd="$(:util:secrets SUDO)"
         if [ $? -eq ${CODE_SUCCESS} ]; then
-            local hostname=$1
-            shift
-
             local prompt="$(printf ".\r")"
             local lckfile=$(mktemp)
-            :ssh:pipewrap "${passwd}" "${lckfile}" | (
-                :ssh:connect ${hostname} sudo -p "${prompt}" -S ${*}
-                e=$?
-                rm -f ${lckfile}
-                exit $e
-            )
+
+            local hnh=$2
+            local tldid
+            tldid=$(:dns:qualified ${hnh})
+            if [ $? -eq ${CODE_SUCCESS} ]; then
+                local fqdn=$2
+                shift 2
+                :ssh:pipewrap "${passwd}" "${lckfile}" | (
+                    :ssh:connect ${tldid} ${fqdn} sudo -p "${prompt}" -S ${*}
+                    e=$?
+                    rm -f ${lckfile}
+                    exit $e
+                )
+            else
+                tldid=$1
+                hnh=$2
+                shift 2
+                :ssh:pipewrap "${passwd}" "${lckfile}" | (
+                    :ssh:connect ${tldid} ${hnh} sudo -p "${prompt}" -S ${*}
+                    e=$?
+                    rm -f ${lckfile}
+                    exit $e
+                )
+            fi
+
             e=$?
         fi
     fi
@@ -68,70 +141,90 @@ function :ssh:sudo() {
     return $e
 }
 
-function ssh:sudo:usage() { echo "<host-hint> <cmd>"; }
+function ssh:sudo:usage() { echo "<tldid> <host-hint> <cmd>"; }
 function ssh:sudo() {
     local -i e=${CODE_DEFAULT}
 
-    if [ $# -ge 2 ]; then
-        local hosthint=$1
-        local -a hostnames=( $(:dns:qdn ${hosthint}) )
-        if [ ${#hostnames[@]} -gt 1 ]; then
-            cpf WARN "More than one match"
-            local hostname
-            for hostname in ${hostnames[@]}; do
-                cpf "    - %{@host:%s}\n" ${hostname}
-            done
-        fi
-        local hostname=${hostnames[0]}
-        shift
+    if [ $# -gt 2 ]; then
+        local tldid=$1
+        local hnh=$2
+        shift 2
 
-        theme INFO "Connecting to ${hostname}..."
-        :ssh:sudo ${hostname} ${*}
-        e=$?
+        local tld=${USER_TLDS[${tldid}]}
+        if [ ${#tld} -gt 0 ]; then
+            local -a qdns=( $(:dns:qdn ${tldid} ${hnh}) )
+            if [ ${#qdns[@]} -gt 1 ]; then
+                cpf WARN "More than one match"
+                local qdn
+                for qdn in ${qdns[@]}; do
+                    cpf "    - %{@host:%s}\n" ${qdn}
+                done
+            fi
+            local qdn=${qdns[0]}
+
+            theme INFO "Connecting to ${qdn}..."
+            :ssh:sudo ${tldid} ${hnh} ${*}
+            e=$?
+        else
+            theme ERR "Invalid TLD identifier \'${tldid}'"
+            e=${CODE_FAILURE}
+        fi
     fi
 
     return $e
 }
 
-function ssh:connect:usage() { echo "<hosthint>"; }
+function ssh:connect:usage() { echo "<tldid> <hnh>"; }
 function ssh:connect() {
     local -i e=${CODE_DEFAULT?}
 
-    if [ $# -ge 1 ]; then
-        if [[ $1 =~ [^\.]+\. ]]; then
+    if [ $# -ge 2 ]; then
+        local hnh=$2
+        local tldid
+        tldid=$(:dns:qualified ${hnh})
+        if [ $? -eq ${CODE_SUCCESS} ]; then
             :ssh:connect $*
             e=$?
-        elif [ $# -ge 1 ]; then
-            core:import dns
+        elif [ $# -ge 2 ]; then
+            tldid=$1
+            shift 2
 
-            local -a hostnames=( $(:dns:qdn ${1}) )
-            local hostname
+            local tld=${USER_TLDS[${tldid}]}
 
-            if [ ${#hostnames[@]} -gt 0 ]; then
-                shift
-                if [ ${#hostnames[@]} -gt 1 ]; then
-                    cpf WARN "More than one match"
-                    for hostname in ${hostnames[@]}; do
-                        cpf "    - %{@host:%s}\n" ${hostname}
+            if [ ${#tld} -gt 0 ]; then
+                local qdn
+                local -a qdns=( $(:dns:qdn ${tldid} ${hnh}) )
+                if [ ${#qdns[@]} -gt 0 ]; then
+                    if [ ${#qdns[@]} -gt 1 ]; then
+                        cpf WARN "More than one match"
+                        for qdn in ${qdns[@]}; do
+                            cpf "    - %{@host:%s}\n" ${qdn}
+                        done
+                    fi
+
+                    if [ $# -eq 0 ]; then
+                        theme INFO "Connecting to ${qdns[0]} $#..."
+                    fi
+
+                    :ssh:connect ${tldid} ${hnh} $*
+                    e=$?
+                    if [ $e -eq 255 ]; then
+                        theme ERR "Failed to connect to \`${qdns[0]}'"
+                    elif [ $e -ne ${CODE_SUCCESS?} ]; then
+                        theme WARN "Connection to ${qdns[0]} terminated with error code \`$e'"
+                    fi
+                elif [ ${#qdns[@]} -gt 0 ]; then
+                    for qdn in ${qdns[@]}; do
+                        read record context query sdn ip <<< "$(:dns:lookup P a ${qdn})"
+                        printf "$(basename $0) ssh connect %-48s #. %s\n" "${qdn} $*" ${ip}
                     done
+                    e=${CODE_SUCCESS}
+                else
+                    theme ERR "Failed to resolve any host matching \`${hnh}'"
+                    e=${CODE_FAILURE}
                 fi
-                theme INFO "Connecting to ${hostnames[0]}..."
-
-                :ssh:connect ${hostnames[0]} $*
-                e=$?
-                if [ $e -eq 255 ]; then
-                    theme ERR "Failed to connect to \`${hostnames[0]}'"
-                elif [ $e -ne ${CODE_SUCCESS?} ]; then
-                    theme WARN "Connection to ${hostnames[0]} terminated with error code \`$e'"
-                fi
-            elif [ ${#hostnames[@]} -gt 0 ]; then
-                for hostname in ${hostnames[@]}; do
-                    read record context query sdn ip <<< "$(:dns:lookup P a ${hostname})"
-                    printf "$(basename $0) ssh connect %-48s #. %s\n" "${hostname} $*" ${ip}
-                done
-                e=${CODE_SUCCESS}
             else
-                theme ERR "Failed to resolve any host matching \`$1'"
+                theme ERR "Invalid TLD identifier \'${tldid}'"
                 e=${CODE_FAILURE}
             fi
         fi
@@ -145,11 +238,13 @@ function ssh:cluster:alert() {
 DEPR This function has been deprecated in favour of tmux.
 !
 }
-function ssh:cluster:usage() { echo "<hosthint> [<hosthint> [...]]"; }
+function ssh:cluster:usage() { echo "<hnh> [<hnh> [...]]"; }
 function ssh:cluster() {
     local -i e=${CODE_DEFAULT?}
 
     core:import hgd
+
+    local tldid=m
 
     if [ $# -eq 1 ]; then
         local hgd=$1
@@ -162,12 +257,12 @@ function ssh:cluster() {
             e=${CODE_FAILURE}
         fi
     elif [ $# -gt 1 ]; then
-        local -a hostnames
-        local hosthint
-        for hosthint in $@; do
-            hostnames=( ${hostnames[@]} $(:dns:qdn ${hosthint}) )
+        local -a qdns
+        local hnh
+        for hnh in $@; do
+            qdns=( ${qdns[@]} $(:dns:qdn ${tldid} ${hnh}) )
         done
-        cssh ${hostnames[@]}
+        cssh ${qdns[@]}
         e=$?
     fi
 
@@ -229,7 +324,7 @@ function ::ssh:tmux() {
             tmux attach-session -t "${session}"
             e=$?
         else
-            core:raise ${EXCEPTION_BAD_FN_CALL}
+            core:raise EXCEPTION_BAD_FN_CALL
         fi
     else
         local -i e=${CODE_FAILURE?}
